# add using kubectl apply -f custom_metrics_global.yaml

kind: ConfigMap
apiVersion: v1
metadata:
  name: dynatrace-sli-config
  namespace: keptn
data:
  custom-queries: |
    throughput: "com.dynatrace.builtin:service.requestspermin,count,0"
    error_count_4xx: "com.dynatrace.builtin:service.errorcounthttp4xx,,0"
    error_count_5xx: "com.dynatrace.builtin:service.errorcounthttp5xx,,0"