apiVersion: v1
kind: Service
metadata:
  name: dynatrace-sli-service
  namespace: keptn
  labels:
    run: dynatrace-sli-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: dynatrace-sli-service